on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: CI

env:
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
          - beta
    steps:
      - uses: extractions/setup-just@v1
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run cargo build
        run: just build

  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        steps:
          - name: cargo check
            run: just check
          - name: cargo hack check
            run: just check-hack-powerset
            hack: true
          - name: cargo hack check --each-feature
            run: just check-hack-each
            hack: true
          - name: cargo hack check --tests
            run: just check-hack-tests
          - name: cargo doc
            run: just docs
    steps:
      - uses: extractions/setup-just@v1
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
        if: matrix.steps.hack
      - name: ${{ matrix.steps.name }}
        run: ${{ matrix.steps.run }}

  msrv:
    name: MSRV 1.74
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.74.0
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run cargo build
        run: just msrv

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build cargo tests
        run: cargo test --features axum,sni,tls,tls-ring,mocks --no-run

      - name: Run cargo test
        run: cargo test --features axum,sni,tls,tls-ring,mocks

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        if: github.repository_owner == 'linode-sokka'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

      - name: Run cargo clippy
        if: github.repository_owner != 'linode-sokka'
        run: cargo clippy --all-features -- -D warnings

  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check bans licenses sources
